"""Force-fix Importing required libraries cells — OpenAI shim, no IBM runtime imports."""

from __future__ import annotations

import json
from pathlib import Path

NOTEBOOK_DIR = Path(__file__).resolve().parent

LANGCHAIN_IMPORT_CELL = """# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
import os
os.environ['ANONYMIZED_TELEMETRY'] = 'False'

# === LOCAL PROVIDER: OpenAI via watson_llm shim (no IBM API / no langchain_ibm) ===
from watson_llm import GenParams, EmbedTextParamsMetaNames, make_watsonx_llm, make_watsonx_embeddings
"""

IN_CONTEXT_IMPORT_CELL = """# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# === LOCAL PROVIDER: OpenAI via watson_llm shim (no IBM API / no langchain_ibm) ===
from watson_llm import GenParams, EmbedTextParamsMetaNames, make_watsonx_llm, make_watsonx_embeddings

from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableSequence
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_classic.chains import LLMChain
"""

OLD_MARKERS = (
    "from ibm_watsonx_ai.foundation_models import ModelInference",
    "from ibm_watsonx_ai.foundation_models import Model",
    "from ibm_watsonx_ai.foundation_models.utils.enums import ModelTypes",
    "from langchain_ibm import WatsonxLLM",
    "from ibm_watson_machine_learning.foundation_models.extensions.langchain import WatsonxLLM",
    "from langchain_ibm import WatsonxEmbeddings",
)


def _is_langchain_import_cell(src: str) -> bool:
    """Coursera 'Importing required libraries' code cell (langchain lab)."""
    return "filterwarnings('ignore')" in src and "langchain_core" not in src and (
        any(m in src for m in OLD_MARKERS) or "make_watsonx_llm" in src
    )


def _to_lines(text: str) -> list[str]:
    lines = text.splitlines(keepends=True)
    if text and not text.endswith("\n") and lines:
        lines[-1] = lines[-1].rstrip("\n")
    return lines or [""]


def patch_file(path: Path) -> int:
    nb = json.loads(path.read_text(encoding="utf-8"))
    changed = 0
    for cell in nb["cells"]:
        if cell.get("cell_type") != "code":
            continue
        src = "".join(cell.get("source", []))
        if "in_context" in path.name:
            if cell.get("cell_type") != "code" or "filterwarnings" not in src:
                continue
            replacement = IN_CONTEXT_IMPORT_CELL
        elif not _is_langchain_import_cell(src):
            continue
        else:
            replacement = LANGCHAIN_IMPORT_CELL
        if replacement.strip() == src.strip():
            continue
        cell["source"] = _to_lines(replacement)
        cell["outputs"] = []
        cell["execution_count"] = None
        changed += 1
    if changed:
        path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    return changed


def main() -> None:
    paths = [
        NOTEBOOK_DIR / "sean_langchain_lab.ipynb",
        NOTEBOOK_DIR / "sean_in_context_lab.ipynb",
        NOTEBOOK_DIR / ".ipynb_checkpoints" / "sean_langchain_lab-checkpoint.ipynb",
        NOTEBOOK_DIR / ".ipynb_checkpoints" / "sean_in_context_lab-checkpoint.ipynb",
    ]
    for path in paths:
        if not path.exists():
            print("skip", path.name)
            continue
        n = patch_file(path)
        print(f"{path.name}: {n} import cell(s) fixed")

    # Also run full openai patch on all notebooks
    import patch_notebooks_openai

    patch_notebooks_openai.main()


if __name__ == "__main__":
    main()